### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by SebastianSchuetze** [Azure/azure-blueprints#1]
Hi! What kind of contributions can somebody make for blueprints?
Do you search for samples or PowerShell code?

**Comment by SebastianSchuetze** [comment]
@ajf214 you are the only contributor here. Is this repo owned by you? Do you have any idea what is expected to be in that repository?

**Comment by alex-frankel** [comment]
Hi @SebastianSchuetze - apologies for the delay. At the moment, we are making limited use of this repo, but we will be moving everything from here (https://github.com/ajf214/personal-arm-templates) over to it sometime in the next week or so. So you can choose to contribute there now, or contribute here once that is done.

Are you looking for powershell examples for working with blueprints?

**Comment by SebastianSchuetze** [comment]
Thanks @alex-frankel. PowerShell example don't exist much I guess since the PS module is in preview and can only assign blueprints. But I'd like to see same good examples of standardized architecture for certain application. 

Something like:

- App-Gatgeway with Vnet, Subnets and VM (possibly DB) behind with properly assigned security-related policies (deployifnotexists), which can go the full way, from creating RGs up to adding proper tags and so on.
- Properly deployed DevTestLab with Images + RABAC + Policies for easy use, when having a workshop in-house / or as consultancy

I think the use cases are endless, but examples like done in the quickstart-templates for ARM template would be great. Actually, if it would be possible to extend the quickstart-template for ARM with blueprints somehow, that would be awesome.

I am myself writing an [Azure DevOps task](https://github.com/RazorSPoint/azure-devops-azure-policy-extension/tree/topic/AzureBluePrint/src/AzureBlueprints/AzureBlueprintsV1) to deploy blueprints, but the PS module is lacking the "New-AzBluePrint" cmdlet to make it proper. I have to use Rest API myself to make it work. ;-)

**Comment by SebastianSchuetze** [comment]
Btw. I would even suggest to use a similiar structure for blueprints like done in the [ARM quickstart-template](https://github.com/Azure/azure-quickstart-templates).

**Comment by alex-frankel** [comment]
Ok - this is all great feedback.

We only have a few powershell examples [here](https://github.com/ajf214/personal-arm-templates/tree/master/Boilerplate/Pipelines) - which is for setting up a build/release pipeline, but you are right that we are limited right now on cmdlet coverage.

BTW, we have someone internal (not on the blueprints team) who is also working on DevOps tasks for blueprints. Would you like me to connect you?

**Comment by SebastianSchuetze** [comment]
Yes, that would be very nice! Maybe I can support.

**Comment by alex-frankel** [comment]
@neilpeterson FYI - you two are both working on Blueprints extensions for DevOps :) There's probably a way to avoid some duplicate effort here.

@SebastianSchuetze  Going to close this as I have now moved all the blueprints-as-code content here. There is a folder of examples which you are very welcome to contribute to. Just fork master and submit a PR.
