### ISSUE TITLE
assignBlueprint.ps1 is empty

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-blueprints#11]
Not sure if this should be an empty file or not

**Comment by alex-frankel** [comment]
I'm going to delete this file. Use this file instead which basically does the same thing, but assumes you are using a service principal. If you want to run it locally with your personal user credentials, you can comment the block for logging into the service principal

**Comment by kilasuit** [comment]
@alex-frankel looks like you missed a link to the file to use instead of the file I raised this against
