### ISSUE TITLE
How to create an artifact with an initiative using json?

### ISSUE THREAD

**Issue by jpendyala** [Azure/azure-blueprints#18]
I'm working on Automation of blueprints and as part of that I would like to create the artifacts using the json files as shown in https://github.com/Azure/azure-blueprints. I was able to create a policy and add it to the blueprint but I'm unable to add an initiative with parameters?

```json
{
    "kind": "policyAssignment",
    "properties": {
        "displayName": "nist-blueprint-template-bp-Audit NIST SP 800-53 R4 controls",
        "description": "This initiative includes audit and VM Extension deployment policies that address a subset of NIST SP 800-53 R4 controls.",
        "policyDefinitionId": "/providers/Microsoft.Authorization/policySetDefinitions/cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f",
        "parameters": {
            "logAnalyticsWorkspaceId": {
                "value": "[parameters('logAnalyticsWorkspaceId')]"
            },
            "listOfResourceTypes": {
                "metadata": {
                    "displayName": "Resource Types",
                    "strongType": "resourceTypes"
                  },
                "value": "[parameters('listOfResourceTypes')]"
            },
            "MembersToExclude": {
                "value": "[parameters('MembersToExclude')]"
            },
            "MembersToInclude": {
                "value": "[parameters('MembersToInclude')]"
            }
        }
    }
}
```
Is this a proper way to create initiative as an artifact?

And I get the below error when trying to create the blueprint using the REST API:
`
 {'error': {'code': 'InvalidArtifact', 'message': "This artifact is invalid. Error: 'Parameter 'logAnalyticsWorkspaceId' does not exist in the policy definition specified by blueprint artifact '_Audit-NIST-SP-800-53-R4-controls'.'"}}
`

**Comment by alex-frankel** [comment]
The error you are getting is saying the policy initiative does not have a parameter called logAnalyticsWorkspaceId.  I looked at the initiative and it looks like that parameter is called logAnalyticsWorkspaceIdforVMReporting

Can you try that instead and see if it works?

**Comment by alex-frankel** [comment]
Here is a gist with the full policy-initiative json for reference:
https://gist.github.com/alex-frankel/7c2aa7324ef82720ff8975014bbf7df4

**Comment by jpendyala** [comment]
sure @alex-frankel , thanks for the quick reply. Let me try and get back to you!

**Comment by jpendyala** [comment]
How were you able to find this? It did go through, however, I encountered a similar error with an other tag

**Comment by jpendyala** [comment]
The gist you provided is very helpful. How to find more for other initiatives? and how to find the correct parameter for others?

**Comment by alex-frankel** [comment]
You can get the actual JSON of any built-in (or custom) initiative definition by doing the following:
 az policy set-definition show -n "cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f" > policy-set.json

somewhat confusingly an initiative in the portal is called a policy-set in our backend.

Glad you were able to get this working.
