### ISSUE TITLE
Can artifacts be organized into subfolders?

### ISSUE THREAD

**Issue by tanzencoder** [Azure/azure-blueprints#24]
For example I have roughly 20 function apps that get deployed into individual resource groups in addition to many other resources for an enterprise solution. Can the resource group artifacts be group like artifacts/functions/... my artifacts?

**Comment by alex-frankel** [comment]
It is a good idea, but not likely something we are going to implement based on current priorities. It'd be a great one to submit a PR for :)

**Comment by tanzencoder** [comment]
@alex-frankel I will have to look into that, sure would make life easier.

**Comment by filizt** [comment]
> It is a good idea, but not likely something we are going to implement based on current priorities. It'd be a great one to submit a PR for :)
> 
> EDIT: actually, looks like we may have just gotten a [PR](https://github.com/Azure/azure-powershell/commit/2700e7287ab991a637f978bffcc84843de33c20e) for this! @filizt is this PR doing what @tanzencoder is looking for?

@alex-frankel yes we have! We have merged it already. @tanzencoder Import-AzBlueprintWithArtifact cmdlet in Version 0.2.10 of Az.Blueprints PS module has the ability to look into sub folders for artifacts. Just use the -IncludeSubFolders switch in the commandline to turn it on.

**Comment by alex-frankel** [comment]
Going to close this - I think this is resolved with the latest release of the modules.
