### ISSUE TITLE
There is no documentation that enumerates all available strongType values for blueprint parameters

### ISSUE THREAD

**Issue by david-jarman** [Azure/azure-blueprints#25]
Docs that should contain possible strongType values:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.blueprint.models.parameterdefinition.strongtype?view=azure-dotnet

https://docs.microsoft.com/en-us/rest/api/blueprints/blueprints/createorupdate#parameterdefinitioncollection

**Comment by alex-frankel** [comment]
@filizt - I thought we did a doc update around parameters - was this supposed to be covered or did I forget about it.

@david-jarman - I believe the available strongTypes are PrincipalId & location today

**Comment by david-jarman** [comment]
@alex-frankel, I've seen other types, such as omsWorkspace, resourceTypes in some other [examples](https://github.com/Azure/azure-blueprints/search?q=strongtype&unscoped_q=strongtype)

**Comment by alex-frankel** [comment]
Ah, resourceTypes too - you are right. omsWorkspace is not implemented. Policy has more strongTypes implemented than we do, so I suspect that's why you are seeing it. It's probably worth opening a separate issue to get rid of that strong type if it is not being used.

**Comment by filizt** [comment]
@alex-frankel  @david-jarman Supported strong types are listed in the API reference documentation now. 
https://docs.microsoft.com/en-us/rest/api/blueprints/blueprints/createorupdate

**Comment by david-jarman** [comment]
Huh, I even linked that in my OP. Maybe my ctrl+f was broken that day!

**Comment by filizt** [comment]
> Huh, I even linked that in my OP. Maybe my ctrl+f was broken that day!

You were right, the strongType definition was not on the reference documentation. We recently updated the page to show it.

**Comment by david-jarman** [comment]
I totally missed the "now" at the end 😄 Thanks so much for adding it!

**Comment by artisticcheese** [comment]
As per link above strongtypes are `ResourceType, principalId and location`. Where does `storageSKUs` falls in place? How do I find out strongtype for AppService SKU for example if it's `ResourceType`?

**Comment by alex-frankel** [comment]
Not sure I'm following @artisticcheese 

Those are the only three strongTypes we support. `storageSKUs` may only work for policy, but it does not for BP. Policy supports a much larger set of strongTypes than blueprints does.
