### ISSUE TITLE
Import-AzBlueprintWithArtifact -IncludeSubFolders only recognizes one artifact when files have common identical names

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-blueprints#27]
If I create a folder structure such as this, where two artifact files have the same name, only one artifact is registered.

artifacts
  |_ artifact1/artifact.json
  |_ artifact2/artifact.json

**Comment by alex-frankel** [comment]
Closing this and tracking here:
https://github.com/Azure/azure-powershell/issues/11146
