### ISSUE TITLE
Blueprint level variables?

### ISSUE THREAD

**Issue by Lutando** [Azure/azure-blueprints#28]
I have a blueprint file that takes in custom parameters as usual. Now I want to have the ability to make blueprint level variables so that i can do string manipulation (to create names of resources eg) so that I can pass these down to arm templates for example. Is there no way to do this? I would prefer if the blueprint held this logic. The resources that eventually get deployed via this blueprint assignment are named by convention according to the blueprint level parameters, ie the resources are name based on the parameter values, it would be nice to define these all in one place rather than duplicating the logic of how resources are named within the artifact templates that live in the blueprint.

Also I have a secondary question. Where can I find the json schema for `blueprint.json` files?

**Comment by alex-frankel** [comment]
Hi Lutando,

Unfortunately, there is not a good way to do what you describe since we don't support any string manipulation functions in blueprints.

Blueprint definition schema is here: https://docs.microsoft.com/en-us/rest/api/blueprints/blueprints/createorupdate

**Comment by Lutando** [comment]
Got ya 👍  thanks!
