### ISSUE TITLE
Build script should contain an example with managed identity

### ISSUE THREAD

**Issue by nbwdk** [Azure/azure-blueprints#3]
$response = Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' -Method GET -Headers @{Metadata="true"}
$content = $response.Content | ConvertFrom-Json
$accessToken = $content.access_token

**Comment by alex-frankel** [comment]
Hi - I'm not exactly sure what the ask is here. Is the goal to use a managed identity from a VM to push the blueprint to Azure?

**Comment by alex-frankel** [comment]
Going to close this - feel free to add more details and we can reopen.
