### ISSUE TITLE
AZ CLI failing

### ISSUE THREAD

**Issue by kfprugger** [Azure/azure-blueprints#35]
when deploying using the AZ CLI, I can't deploy with some vague error regarding properties.

When deploying via the portal using the imported blueprint, I had no issues.

![image](https://user-images.githubusercontent.com/20729981/81736947-5e203c00-9465-11ea-90bc-9d4f63e53898.png)

Also, there are no docs on MS Docs for AZ CLI

**Comment by alex-frankel** [comment]
Can you open the issue here instead: https://github.com/Azure/azure-cli
