### ISSUE TITLE
VSCode extension which interprets blueprint files as valid ARM templates

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-blueprints#37]
Currently one have to use JSON instead of ARM template (despite the fact that actual contents of template contains valid ARM template). Need better tooling support for authoring blueprints artifacts.

**Comment by alex-frankel** [comment]
The plan is to wait until blueprint definitions migrates to templateSpecs. At that point you'll be able to use the ARM Tools extension. Going to close this, but let me know if you need more context
