### ISSUE TITLE
-Whatif parameter for New-AzBlueprintAssignment is not doing anything

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-blueprints#44]
Expectations are that it will show what will happen with deployment, that is resources created/update/deleted but nothing is being shown except `What if: Performing the operation "Create blueprint assignment 'BP-Assign-Dev'" on target "90be46f1-376c-4619-8e6f-4a0635b86ab3".`
Not sure what is the point of that operation.

**Comment by alex-frankel** [comment]
`-WhatIf` is a powershell-ism that we take advantage of for ARM template deployments by calling the ARM Template what-if API when you use the `-WhatIf` or `-Confirm` flags, but there is no equivalent what-if functionality for blueprints. I think you will see `-WhatIf` in most Az cmdlets that basically do nothing. Does that help clarify?

**Comment by artisticcheese** [comment]
OK, just confirming what I'm seeing is what is expected and not some sort of bug
